### ISSUE TITLE
nueva versión para nuevos DNIe

### ISSUE THREAD

**Issue by pr-apes** [albfernandez/clienteafirma-deb-package#12]
@albfernandez,

sería muy útil (entre otros, para solucionar problemas con DNIe nuevos [ctt-gob-es/clienteafirma#145]) que pudieras sacar una nueva versión para _Debian_ estable.

Así también podríamos probar si la versión 1.7 funcionará bien en su momento.

Muchas gracias por tu gran trabajo.

**Comment by albfernandez** [comment]
Hola

Tengo en pre-release una version del estado de git de autoafirma de hace dos meses

https://github.com/albfernandez/clienteafirma-deb-package/releases/tag/v.1.7.202103.1-1

Estoy tratando de generar uno con el estado actual y que solucione los dos problemas de la prerelease:

  -  Puede que algunos archivos dentro del perfil de firefox ~/.mozilla/firefox/xxxxx.default/ se queden con permisos de root tras la instalación, revisar y cambiar el propietario al usuario correspondiente
 -   se queda bloqueado al firmar un archivo local (lanzado como aplicacion). Si se invoca por protocolo funciona correctamente

**Comment by pr-apes** [comment]
Siento el retraso en la respuesta, pero me ha sido imposible antes.

He probado tu versión previa y a mí me funciona firmando en local (con DNI nuevo).

Sin embargo, no hay modo de que conecte Firefox llame a AutoFirma (la instalación de la versión previa me da error y no sé de dónde instalar el certificado raíz de AutoFirma para Firefox).

Lo de los permisos y lo he solucionado a la brava (no sé si hay algún problema):

```
chown usuario.usuario -R ~/.mozilla/firefox/*
```

Sería interesante actualizar el código, por ver si alguna de las cosas han mejorado en el código de AutoFirma.

Muchas gracias por tu ayuda.
